version: '3.7'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - mongo
    environment:
      PORT: 3000
  www:
    build: ./www
    ports:
      - '80:80'
    links:
      - api
    depends_on:
      - api
    environment:
      PORT: 80
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    image: mongo:4.2.0
